### ISSUE TITLE
Cannot import wallets with .json extension

### ISSUE THREAD

**Issue by Dainius14** [radixdlt/radixdlt-wallet-android#20]
Importing a wallet with .json extension instead of .key extension does nothing - I get back to import/create screen without any message. Simply changing the extension of that same key file to .key - works fine.

**Comment by MarcRubio** [comment]
Strange as file extension should not matter and hasn't affected in the past. The desktop wallet generates a .json file and this could be imported without any problems. I also changed the extension to .json and it worked.

I think this may be related to another bug due to the time lock and I will be issuing an update very soon which fixes it.

You can for now try clearing the app data in App Info in the Android Settings and try importing the .json file. You can access this menu normally by holding on the app icon in you home screen or app drawer.

If this fixes the issue, for now don't disable the password as that is what causes the bug. Will be fixed in the next update!

If it doesn't work, can you provide brand of your phone and model with Android version you are running?

**Comment by Dainius14** [comment]
Clearing app data seems to fix it and now any file with any extension works. I was sure this must have been bug :)

**Comment by MarcRubio** [comment]
Ok thanks, this is definitely the bug I thought of. Will do an update very soon which fixes it! 
Thanks for reporting
